version: '3.9'

services:
  soketi:
    container_name: soketi
    build:
      context: .
      dockerfile: soketi.Dockerfile
    restart: always
    ports:
      - '6001:6001'

  caddy:
    container_name: caddy
    image: caddy:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /home/ubuntu/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/ubuntu/caddy/data:/data
      - /home/ubuntu/caddy/config:/config
